import { Alegreya_Sans } from "next/font/google";
import { Rubik_Glitch } from "next/font/google";
import { Sofia } from "next/font/google";
import { Major_Mono_Display } from "next/font/google";
import { Limelight } from "next/font/google";
import "./globals.css";
import "./home.css"
import "./membership.css"
import "./signIn.css"
import "./dashboard.css"
import "../icofont/icofont.min.css"

import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";




const mjd = Major_Mono_Display({ subsets: ["latin"], weight: ["400"], variable: "--font-md" });
const limelight = Limelight({ subsets: ["latin"], weight: ["400"], variable: "--font-l" });
const alegreya = Alegreya_Sans({subsets: ["latin"], weight: ['100', '300', '400', '500', '800', '700'], variable: "--font-aleg"})
const rubik = Rubik_Glitch({ subsets: ["latin"], weight: ["400"], variable: "--font-r" });
const sofia = Sofia({ subsets: ["latin"], weight: ["400"], variable: "--font-sf" });


export const metadata = {
  title: "Dmayor Fitness Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        signIn: { baseTheme: [dark] }
      }}  
    >
      <html lang="en">
        <body className={`${alegreya.variable} ${rubik.variable} ${sofia.variable} ${limelight.variable} ${mjd.variable}`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
